#MOSTLY COPIED FROM STARFIELD COMMUNITY PATCH

name: Build Release

# Controls when the workflow will run
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (defaults to "Nightly")'
        required: false
      publish-release:
        description: Publish Release?
        type: boolean
        default: true
      spriggit_tool_version:
        description: Spriggit version (optional)
        required: false

jobs:
  # possibly change this to check for spriggit and papyrus individually
  check-changes:
    name: Check for recent changes
    if: ${{ github.event_name != 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    outputs: 
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes last 24 hours
        id: should_run
        shell: bash
        run: |
          git log --since="1 days ago" --name-only
          echo "should_run=$(git log --since="1 days ago" --name-only | grep "" -c)" >> "$GITHUB_OUTPUT"
  build-plugin:
    name: Build ESP from Spriggit files
    needs: check-changes
    if: ${{ needs.check-changes.outputs.should_run >= 1 || (github.event_name == 'workflow_dispatch' && always()) }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Output Inputs
        run: |
          echo "GitHub Event Inputs: ${{ toJSON(github.event.inputs) }}"
          echo "Inputs: ${{ toJSON(inputs) }}"


      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy to Pack Folder
        shell: bash
        run: mkdir ${{ github.workspace }}/to-pack
      
      - name: Fetch spriggit
        shell: bash
        run: gh release download -O .github/spriggit.zip -p 'SpriggitLinuxCLI.zip' -R Mutagen-Modding/Spriggit ${{ inputs.spriggit_tool_version }}
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: Extract Spriggit Zip
        shell: bash
        run: 7z x .github/spriggit.zip -o.github/spriggit

      - name: fix spriggit permission
        shell: bash
        run: chmod +x .github/spriggit/Spriggit.CLI

      - name: run spriggit
        shell: bash
        run: .github/spriggit/Spriggit.CLI deserialize --InputPath "ESP Patch" --OutputPath "${{ github.workspace }}/to-pack/SexLab-Parasites-UD.esp"

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
            name: plugin
            path: ${{ github.workspace }}/to-pack/SexLab-Parasites-UD.esp

  package-mod:
    name: Package all necessary files
    runs-on: windows-latest
    needs: [build-plugin]
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download Compiled Plugin
        uses: actions/download-artifact@v4
        with:
          name: plugin

      - name: Create packing structure
        shell: bash
        run: |
          mkdir "${{ github.workspace }}\to-pack"
          mkdir "${{ github.workspace }}\to-pack\Data"
          cp "SexLab-Parasites-UD.esp" "${{ github.workspace }}\to-pack\Data\SexLab-Parasites-UD.esp"
          cp -r "Sound" "${{ github.workspace }}\to-pack\Data\Sound"
          cp -r "Scripts" "${{ github.workspace }}\to-pack\Data\Scripts"
          ls -R "${{ github.workspace }}\to-pack"

      - name: Zip release files
        uses: vimtor/action-zip@v1.2
        with:
          files: to-pack/
          dest: UnforgivingParasites-${{inputs.version || 'nightly'}}.zip

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: UnforgivingParasites-${{inputs.version || 'nightly'}}
          path: UnforgivingParasites-${{inputs.version || 'nightly'}}.zip

      - name: Remove temporary artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            plugin

  share-release:
    name: Share release
    needs: [package-mod]
    if: ${{ inputs.publish-release == true && (needs.check-changes.outputs.should_run >= 1 || (github.event_name == 'workflow_dispatch' && always())) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: UnforgivingParasites-${{inputs.version || 'nightly'}}

      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag-name: ${{inputs.version || 'nightly'}}
          github-token: $${{ github.token }}
          delete_release: true
      
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          allowUpdates: true
          name: ${{inputs.version || 'nightly'}}
          draft: false
          body: 'Latest release of Unforgiving Parasites'
          tag: ${{inputs.version || 'nightly'}}
          prerelease: true
          makeLatest: false
          removeArtifacts: true
          replaceArtifacts: true
          artifactErrorsFailBuild: true
          artifacts: UnforgivingParasites-${{inputs.version || 'nightly'}}.zip

      - name: Remove temporary artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: UnforgivingParasites-${{inputs.version || 'nightly'}}
